In [1]:
# iris dataset
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
type(iris) # sklearn datatype for storing dataset and there atributes in sklearn Bunch 

sklearn.utils.Bunch

In [3]:
print(iris.data) # one of the atributes is data 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
# each row is an observation known as sample
# each column is a feature here in iris dataset has 4 column so 4 feature 
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
# linear discriminant analysis is used to make prediction on this dataset
# if the dataset doesent have the species it can be classified into an unsupervised learning 
# by tempting to cluster the sample into meaningful groups

In [5]:
print(iris.target) # print integrs representing the species of each observation 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
# print the encoding scheme for species : 0=sestos 1=versicolour 2=verginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [7]:
# each value we are predicting is response ( also known as target, outcome, label, dependent variable )

# the two type of supervised learning 
## classification - in which the responses is categorical (finite unordered set)
## Regression - in which the responses are ordered and continuous 

### inorder to tell what we should carry on with calssification or regression 
### we have see the dataset and understand which would work the best for the dataset 

# Requierments for woking with  data in scikit-learn
 
 ##    1. feature and responses are seperate objects
 ##    2. feature and responses should be numeric 
 ##    3. feature and reponses should be numpy arrays
 ##    4. feature and responses should have specific shapes

In [9]:
# first we should check the type of features and reponses
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
# check the shape of the data 
print(iris.data.shape)

(150, 4)


In [11]:
# check the shape of responses (here it is one dimensional matching the number of observation)
print(iris.target.shape)

(150,)


In [ ]:
# store feature matrix in x 
X = iris.data

# store responses matrix in y
Y = iris.target